baseURL = "https://guillem-gelabert.github.io"
enableEmoji = true
enableRobotsTXT = false
languageCode = "en-us"
summarylength = 30
theme = "anatole"
title = "Fullstack Developer"

[params]
author = "Guillem Gelabert Sunyer"
customCss = []
customJs = []
description = "Fullstack Developer"
displayMode = "dark"
keywords = ""
profilePicture = "images/profile.jpg"
title = "Guillem Gelabert"

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/guillem-gelabert/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/guillem-gelabert"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:gelabert.guillem+blog@gmail.com"

## Menu items

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 100

[[menu.main]]
identifier = "categories"
name = "Series"
url = "/categories"
weight = 200

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 300
